src/Entity/Barang.php
<?php

namespace App\Entity;

use App\Repository\BarangRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BarangRepository::class)]
class Barang
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_barang = null;

    #[ORM\Column(length: 255)]
    private ?string $nama_barang = null;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangMasuk::class, orphanRemoval: true)]
    private Collection $barangMasuks;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangKeluar::class, orphanRemoval: true)]
    private Collection $barangKeluars;

    public function __construct()
    {
        $this->barangKeluars = new ArrayCollection();
        $this->barangMasuks = new ArrayCollection();
    }
    
    public function getBarangKeluars(): Collection
    {
        return $this->barangKeluars;
    }

    public function getBarangMasuks(): Collection
    {
        return $this->barangMasuks;
    }

    public function getIdBarang(): ?int
    {
        return $this->id_barang;
    }

    public function setIdBarang(?int $id_barang): self
    {
        $this->id_barang = $id_barang;
        return $this;
    }

    public function getNamaBarang(): ?string
    {
        return $this->nama_barang;
    }

    public function setNamaBarang(string $nama_barang): static
    {
        $this->nama_barang = $nama_barang;

        return $this;
    }
}

src/Entity/BarangMasuk.php
<?php

namespace App\Entity;

use App\Repository\BarangMasukRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BarangMasukRepository::class)]
class BarangMasuk
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_masuk = null;

    // #[ORM\Column]
    // private ?int $id_barang = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $tgl_masuk = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $spesifikasi = null;

    #[ORM\Column(length: 100)]
    private ?string $kondisi = null;

    #[ORM\Column]
    private ?int $jml_masuk = null;

    #[ORM\ManyToOne(targetEntity: Barang::class, inversedBy: 'barangKeluars')]
    #[ORM\JoinColumn(nullable: false, name: 'id_barang', referencedColumnName: 'id_barang')]
    private ?Barang $barang = null;

    public function getBarang(): ?Barang
    {
        return $this->barang;
    }

    public function setBarang(?Barang $barang): self
    {
        $this->barang = $barang;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id_masuk;
    }

    // public function getIdBarang(): ?int
    // {
    //     return $this->id_barang;
    // }

    // public function setIdBarang(int $id_barang): static
    // {
    //     $this->id_barang = $id_barang;

    //     return $this;
    // }

    public function getTglMasuk(): ?\DateTimeInterface
    {
        return $this->tgl_masuk;
    }

    public function setTglMasuk(\DateTimeInterface $tgl_masuk): static
    {
        $this->tgl_masuk = $tgl_masuk;

        return $this;
    }

    public function getSpesifikasi(): ?string
    {
        return $this->spesifikasi;
    }

    public function setSpesifikasi(string $spesifikasi): static
    {
        $this->spesifikasi = $spesifikasi;

        return $this;
    }

    public function getKondisi(): ?string
    {
        return $this->kondisi;
    }

    public function setKondisi(string $kondisi): static
    {
        $this->kondisi = $kondisi;

        return $this;
    }

    public function getJmlMasuk(): ?int
    {
        return $this->jml_masuk;
    }

    public function setJmlMasuk(int $jml_masuk): static
    {
        $this->jml_masuk = $jml_masuk;

        return $this;
    }
}

src/Form/BarangMasukType.php
<?php

namespace App\Form;

use App\Entity\Barang;
use App\Entity\BarangMasuk;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BarangMasukType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_barang')
            ->add('tgl_masuk', null, [
                'widget' => 'single_text',
            ])
            ->add('spesifikasi')
            ->add('kondisi')
            ->add('jml_masuk')
            ->add('barang', EntityType::class, [
                'class' => Barang::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => BarangMasuk::class,
        ]);
    }
}

src/Controller/BarangMasukController.php
<?php

namespace App\Controller;

use App\Entity\BarangMasuk;
use App\Form\BarangMasukType;
use App\Repository\BarangMasukRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/barang_masuk')]
class BarangMasukController extends AbstractController
{
    #[Route('/', name: 'app_barang_masuk_index', methods: ['GET'])]
    public function index(BarangMasukRepository $barangMasukRepository): Response
    {
        return $this->render('barang_masuk/index.html.twig', [
            'barang_masuks' => $barangMasukRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_barang_masuk_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $barangMasuk = new BarangMasuk();
        $form = $this->createForm(BarangMasukType::class, $barangMasuk);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($barangMasuk);
            $entityManager->flush();

            return $this->redirectToRoute('app_barang_masuk_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('barang_masuk/new.html.twig', [
            'barang_masuk' => $barangMasuk,
            'form' => $form,
        ]);
    }

    #[Route('/{id_masuk}', name: 'app_barang_masuk_show', methods: ['GET'])]
    public function show(BarangMasuk $barangMasuk): Response
    {
        return $this->render('barang_masuk/show.html.twig', [
            'barang_masuk' => $barangMasuk,
        ]);
    }

    #[Route('/{id_masuk}/edit', name: 'app_barang_masuk_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BarangMasuk $barangMasuk, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BarangMasukType::class, $barangMasuk);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_barang_masuk_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('barang_masuk/edit.html.twig', [
            'barang_masuk' => $barangMasuk,
            'form' => $form,
        ]);
    }

    #[Route('/{id_masuk}', name: 'app_barang_masuk_delete', methods: ['POST'])]
    public function delete(Request $request, BarangMasuk $barangMasuk, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$barangMasuk->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($barangMasuk);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_barang_masuk_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/barang_masuk/_delete_form.html.twig
<form method="post" action="{{ path('app_barang_masuk_delete', {'id_masuk': barang_masuk.id_masuk}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ barang_masuk.id_masuk) }}">
    <button class="btn">Delete</button>
</form>

templates/barang_masuk/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/barang_masuk/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BarangMasuk{% endblock %}

{% block body %}
    <h1>Edit BarangMasuk</h1>

    {{ include('barang_masuk/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_barang_masuk_index') }}">back to list</a>

    {{ include('barang_masuk/_delete_form.html.twig') }}
{% endblock %}

templates/barang_masuk/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BarangMasuk index{% endblock %}

{% block body %}
    <h1>BarangMasuk index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id_masuk</th>
                <th>Id_barang</th>
                <th>Tgl_masuk</th>
                <th>Spesifikasi</th>
                <th>Kondisi</th>
                <th>Jml_masuk</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for barang_masuk in barang_masuks %}
            <tr>
                {# <td>{{ barang_masuk.id_masuk }}</td> #}
                {# <td>{{ barang_masuk.idBarang }}</td> #}
                <td>{{ barang_masuk.tglMasuk ? barang_masuk.tglMasuk|date('Y-m-d') : '' }}</td>
                <td>{{ barang_masuk.spesifikasi }}</td>
                <td>{{ barang_masuk.kondisi }}</td>
                <td>{{ barang_masuk.jmlMasuk }}</td>
                <td>
                    <a href="{{ path('app_barang_masuk_show', {'id_masuk': barang_masuk.id}) }}">show</a>
                    <a href="{{ path('app_barang_masuk_edit', {'id_masuk': barang_masuk.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_barang_masuk_new') }}">Create new</a>
{% endblock %}

templates/barang_masuk/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BarangMasuk{% endblock %}

{% block body %}
    <h1>Create new BarangMasuk</h1>

    {{ include('barang_masuk/_form.html.twig') }}

    <a href="{{ path('app_barang_masuk_index') }}">back to list</a>
{% endblock %}

templates/barang_masuk/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BarangMasuk{% endblock %}

{% block body %}
    <h1>BarangMasuk</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_masuk</th>
                <td>{{ barang_masuk.idMasuk }}</td>
            </tr>
            <tr>
                <th>Id_barang</th>
                <td>{{ barang_masuk.idBarang }}</td>
            </tr>
            <tr>
                <th>Tgl_masuk</th>
                <td>{{ barang_masuk.tglMasuk ? barang_masuk.tglMasuk|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Spesifikasi</th>
                <td>{{ barang_masuk.spesifikasi }}</td>
            </tr>
            <tr>
                <th>Kondisi</th>
                <td>{{ barang_masuk.kondisi }}</td>
            </tr>
            <tr>
                <th>Jml_masuk</th>
                <td>{{ barang_masuk.jmlMasuk }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_barang_masuk_index') }}">back to list</a>

    <a href="{{ path('app_barang_masuk_edit', {'id_masuk': barang_masuk.id_masuk}) }}">edit</a>

    {{ include('barang_masuk/_delete_form.html.twig') }}
{% endblock %}