src/Entity/Barang.php
<?php

namespace App\Entity;

use App\Repository\BarangRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BarangRepository::class)]
class Barang
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_barang = null;

    #[ORM\Column(length: 255)]
    private ?string $nama_barang = null;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangMasuk::class, orphanRemoval: true)]
    private Collection $barangMasuks;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangKeluar::class, orphanRemoval: true)]
    private Collection $barangKeluars;

    public function __construct()
    {
        $this->barangKeluars = new ArrayCollection();
        $this->barangMasuks = new ArrayCollection();
    }
    
    public function getBarangKeluars(): Collection
    {
        return $this->barangKeluars;
    }

    public function getBarangMasuks(): Collection
    {
        return $this->barangMasuks;
    }

    public function getIdBarang(): ?int
    {
        return $this->id_barang;
    }

    public function setIdBarang(?int $id_barang): self
    {
        $this->id_barang = $id_barang;
        return $this;
    }

    public function getNamaBarang(): ?string
    {
        return $this->nama_barang;
    }

    public function setNamaBarang(string $nama_barang): static
    {
        $this->nama_barang = $nama_barang;

        return $this;
    }
}

src/Entity/BarangKeluar.php
<?php

namespace App\Entity;

use App\Repository\BarangKeluarRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\PrePersist;

#[ORM\Entity(repositoryClass: BarangKeluarRepository::class)]
class BarangKeluar
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_keluar = null;

    #[ORM\Column]
    private ?int $id_barang = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $tgl_keluar = null;

    #[ORM\Column]
    private ?int $jml_keluar = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $deskripsi = null;

    #[ORM\ManyToOne(targetEntity: Barang::class, inversedBy: 'barangKeluars')]
    #[ORM\JoinColumn(nullable: false, name: 'id_barang', referencedColumnName: 'id_barang')]
    private ?Barang $barang = null;

    public function getId(): ?int
    {
        return $this->id_keluar;
    }

    public function getIdBarang(): ?int
    {
        return $this->id_barang;
    }

    public function setIdBarang(?int $id_barang): static
    {
        $this->id_barang = $id_barang;

        return $this;
    }

    public function getTglKeluar(): ?\DateTimeInterface
    {
        return $this->tgl_keluar;
    }

    // public function setTglKeluar(\DateTimeInterface $tgl_keluar): static
    // {
    //     $this->tgl_keluar = $tgl_keluar;

    //     return $this;
    // }
    #[PrePersist]
    public function setTglKeluarValue(): void 
    {
        $this->tgl_keluar = new \DateTime();
    }


    public function getJmlKeluar(): ?int
    {
        return $this->jml_keluar;
    }

    public function setJmlKeluar(int $jml_keluar): static
    {
        $this->jml_keluar = $jml_keluar;

        return $this;
    }

    public function getDeskripsi(): ?string
    {
        return $this->deskripsi;
    }

    public function setDeskripsi(string $deskripsi): static
    {
        $this->deskripsi = $deskripsi;

        return $this;
    }

    public function getBarang(): ?Barang
    {
        return $this->barang;
    }

    public function setBarang(?Barang $barang): self
    {
        $this->barang = $barang;
        return $this;
    }
}

src/Form/BarangKeluarType.php
<?php

namespace App\Form;

use App\Entity\BarangKeluar;
use App\Entity\Barang;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BarangKeluarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('id_barang', EntityType::class, [
                'class' => Barang::class,
                'choice_label' => 'nama_barang',
                'attr' => ['class' => 'form-control select2 text-capitalize']
            ])
            ->add('jml_keluar', IntegerType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('deskripsi', TextareaType::class, [
                'attr' => ['class' => 'form-control']
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => BarangKeluar::class,
        ]);
    }
}

src/Controller/BarangKeluarController.php
<?php

namespace App\Controller;

use App\Entity\BarangKeluar;
use App\Form\BarangKeluarType;
use App\Repository\BarangKeluarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/barang_keluar')]
class BarangKeluarController extends AbstractController
{
    #[Route('/', name: 'app_barang_keluar_index', methods: ['GET'])]
    public function index(BarangKeluarRepository $barangKeluarRepository): Response
    {
        return $this->render('barang_keluar/index.html.twig', [
            'barang_keluars' => $barangKeluarRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_barang_keluar_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $barangKeluar = new BarangKeluar();
        $form = $this->createForm(BarangKeluarType::class, $barangKeluar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($barangKeluar);
            $entityManager->flush();

            return $this->redirectToRoute('app_barang_keluar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('barang_keluar/new.html.twig', [
            'barang_keluar' => $barangKeluar,
            'form' => $form,
        ]);
    }

    #[Route('/{id_keluar}', name: 'app_barang_keluar_show', methods: ['GET'])]
    public function show(BarangKeluar $barangKeluar): Response
    {
        return $this->render('barang_keluar/show.html.twig', [
            'barang_keluar' => $barangKeluar,
        ]);
    }

    #[Route('/{id_keluar}/edit', name: 'app_barang_keluar_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, BarangKeluar $barangKeluar, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BarangKeluarType::class, $barangKeluar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_barang_keluar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('barang_keluar/edit.html.twig', [
            'barang_keluar' => $barangKeluar,
            'form' => $form,
        ]);
    }

    #[Route('/{id_keluar}', name: 'app_barang_keluar_delete', methods: ['POST'])]
    public function delete(Request $request, BarangKeluar $barangKeluar, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$barangKeluar->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($barangKeluar);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_barang_keluar_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/barang_keluar/_delete_form.html.twig
<form method="post" action="{{ path('app_barang_keluar_delete', {'id_keluar': barang_keluar.id_keluar}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ barang_keluar.id_keluar) }}">
    <button class="btn">Delete</button>
</form>

templates/barang_keluar/_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Form Barang Keluar{% endblock %}

{% block body %}
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>Form Barang Keluar</h1>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        {% if form.vars.value.idKeluar is defined %}
                            <h4>Edit Barang Keluar</h4>
                        {% else %}
                            <h4>Tambah Barang Keluar</h4>
                        {% endif %}
                    </div>
                    <div class="card-body">
                        {{ form_start(form, {'attr': {'class': 'custom-form-class'}}) }}
                        <div class="row">
                            <div class="col-lg-12">
                                {% if app.session.flashBag.has('success') %}
                                    <div class="alert alert-success">
                                        {{ app.session.flashBag.get('success')[0] }}
                                    </div>
                                {% endif %}
                                {% if app.session.flashBag.has('error') %}
                                    <div class="alert alert-danger">
                                        {{ app.session.flashBag.get('error')[0] }}
                                    </div>
                                {% endif %}
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>Nama Barang</label>
                                    {{ form_widget(form.id_barang) }}
                                    {{ form_errors(form.id_barang) }}
                                </div>
                                <div class="form-group">
                                    <label>Jumlah Keluar</label>
                                    {{ form_widget(form.jml_keluar) }}
                                    {{ form_errors(form.jml_keluar) }}
                                </div>
                                <div class="form-group">
                                    <label>Deskripsi</label>
                                    {{ form_widget(form.deskripsi) }}
                                    {{ form_errors(form.deskripsi) }}
                                </div>
                                <div class="form-group text-right">
                                    <button class="btn btn-info mr-1" type="submit">Simpan</button>
                                    <a href="{{ path('app_barang_keluar_index') }}">
                                        <button type="button" class="btn btn-danger" name="batal">Kembali</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/barang_keluar/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit BarangKeluar{% endblock %}

{% block body %}
    <h1>Edit BarangKeluar</h1>

    {{ include('barang_keluar/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_barang_keluar_index') }}">back to list</a>

    {{ include('barang_keluar/_delete_form.html.twig') }}
{% endblock %}

templates/barang_keluar/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}BarangKeluar index{% endblock %}

{% block body %}
    {# <h1>BarangKeluar index</h1> #}

    {# <table class="table">
        <thead>
            <tr>
                <th>Id_keluar</th>
                <th>Id_barang</th>
                <th>Tgl_keluar</th>
                <th>Jml_keluar</th>
                <th>Deskripsi</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for barang_keluar in barang_keluars %}
            <tr>
                <td>{{ barang_keluar.idKeluar }}</td>
                <td>{{ barang_keluar.idBarang }}</td>
                <td>{{ barang_keluar.tglKeluar ? barang_keluar.tglKeluar|date('Y-m-d') : '' }}</td>
                <td>{{ barang_keluar.jmlKeluar }}</td>
                <td>{{ barang_keluar.deskripsi }}</td>
                <td>
                    <a href="{{ path('app_barang_keluar_show', {'id_keluar': barang_keluar.id_keluar}) }}">show</a>
                    <a href="{{ path('app_barang_keluar_edit', {'id_keluar': barang_keluar.id_keluar}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}
    {{ include('layouts/header.html.twig') }}
    {{ include('layouts/navigation.html.twig') }}

     	<!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Daftar Barang Keluar</h1>
          </div>
          
          <div class="section-body">
            <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h4>Barang Keluar</h4>
                      <div class="card-header-action"><a href="{{ path('app_barang_keluar_new') }}"><button class="btn btn-lg btn-info" type="submit"><i class="fas fa-plus"></i> Tambah Baru</button></a></div>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>                                 
                          <tr>
                            <th class="text-center">No</th>
                            <th>Nama Barang</th>
                            <th>Jumlah Keluar</th>
                            <th>deskripsi</th>
                            <th>Tanggal Keluar</th>
                            <th>action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% set counter = 1 %}
                          {% for barang_keluar in barang_keluars %}
                          <tr>
                            <td class="text-center">{{ counter }}</td>
                            {% set counter = counter + 1 %}
                            <td>
                                <span class="text-capitalize">{{ barang_keluar.barang.namaBarang }}</span>
                                 <div class="table-links">
                                  <a href="<?php echo site_url('barang_keluar/ubah/'.$data->id_keluar);?>"><span class="badge badge-primary">Edit <i class="fas fa-pencil-alt"></i></span></a>
                                </div>
                            </td>
                            <td><div class="badge badge-light">{{ barang_keluar.jmlKeluar }}</div></td>
                            <td>{{ barang_keluar.deskripsi }}</td>
                            <td><div class="badge badge-light">{{ barang_keluar.tglKeluar ? barang_keluar.tglKeluar|date('Y-m-d') : 'N/A' }}</div></td>
                            <td>
                               <a href="<?php echo site_url('barang_keluar/ubah/'.$data->id_keluar);?>" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i></a>
                               <a href="<?= site_url('barang_keluar/hapus/'.$data->id_keluar); ?>" class="btn btn-danger btn-action" onclick="return confirm('Yakin Hapus barang?')" data-toggle="tooltip" title="Delete"><i class="fas fa-trash"></i></a>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
    </div>

    {# <a href="{{ path('app_barang_keluar_new') }}">Create new</a> #}
    {{ include('layouts/footer.html.twig') }}
{% endblock %}

templates/barang_keluar/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New BarangKeluar{% endblock %}

{% block body %}
    {{ include('layouts/header.html.twig') }}
    {{ include('layouts/navigation.html.twig') }}

    {{ include('barang_keluar/_form.html.twig') }}

    {{ include('layouts/footer.html.twig') }}

    <a href="{{ path('app_barang_keluar_index') }}">back to list</a>
{% endblock %}

templates/barang_keluar/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}BarangKeluar{% endblock %}

{% block body %}
    <h1>BarangKeluar</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_keluar</th>
                <td>{{ barang_keluar.idKeluar }}</td>
            </tr>
            <tr>
                <th>Id_barang</th>
                <td>{{ barang_keluar.idBarang }}</td>
            </tr>
            <tr>
                <th>Tgl_keluar</th>
                <td>{{ barang_keluar.tglKeluar ? barang_keluar.tglKeluar|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Jml_keluar</th>
                <td>{{ barang_keluar.jmlKeluar }}</td>
            </tr>
            <tr>
                <th>Deskripsi</th>
                <td>{{ barang_keluar.deskripsi }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_barang_keluar_index') }}">back to list</a>

    <a href="{{ path('app_barang_keluar_edit', {'id_keluar': barang_keluar.id_keluar}) }}">edit</a>

    {{ include('barang_keluar/_delete_form.html.twig') }}
{% endblock %}