src/Entity/Barang.php
<?php

namespace App\Entity;

use App\Repository\BarangRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BarangRepository::class)]
class Barang
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_barang = null;

    #[ORM\Column(length: 255)]
    private ?string $nama_barang = null;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangMasuk::class, orphanRemoval: true)]
    private Collection $barangMasuks;

    #[ORM\OneToMany(mappedBy: 'barang', targetEntity: BarangKeluar::class, orphanRemoval: true)]
    private Collection $barangKeluars;

    public function __construct()
    {
        $this->barangKeluars = new ArrayCollection();
        $this->barangMasuks = new ArrayCollection();
    }
    
    public function getBarangKeluars(): Collection
    {
        return $this->barangKeluars;
    }

    public function getBarangMasuks(): Collection
    {
        return $this->barangMasuks;
    }

    public function getIdBarang(): ?int
    {
        return $this->id_barang;
    }

    public function setIdBarang(?int $id_barang): self
    {
        $this->id_barang = $id_barang;
        return $this;
    }

    public function getNamaBarang(): ?string
    {
        return $this->nama_barang;
    }

    public function setNamaBarang(string $nama_barang): static
    {
        $this->nama_barang = $nama_barang;

        return $this;
    }
}

src/Entity/BarangMasuk.php
<?php

namespace App\Entity;

use App\Repository\BarangMasukRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BarangMasukRepository::class)]
class BarangMasuk
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id_masuk = null;

    // #[ORM\Column]
    // private ?int $id_barang = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $tgl_masuk = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $spesifikasi = null;

    #[ORM\Column(length: 100)]
    private ?string $kondisi = null;

    #[ORM\Column]
    private ?int $jml_masuk = null;

    #[ORM\ManyToOne(targetEntity: Barang::class, inversedBy: 'barangKeluars')]
    #[ORM\JoinColumn(nullable: false, name: 'id_barang', referencedColumnName: 'id_barang')]
    private ?Barang $barang = null;

    public function getBarang(): ?Barang
    {
        return $this->barang;
    }

    public function setBarang(?Barang $barang): self
    {
        $this->barang = $barang;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id_masuk;
    }

    // public function getIdBarang(): ?int
    // {
    //     return $this->id_barang;
    // }

    // public function setIdBarang(int $id_barang): static
    // {
    //     $this->id_barang = $id_barang;

    //     return $this;
    // }

    public function getTglMasuk(): ?\DateTimeInterface
    {
        return $this->tgl_masuk;
    }

    public function setTglMasuk(\DateTimeInterface $tgl_masuk): static
    {
        $this->tgl_masuk = $tgl_masuk;

        return $this;
    }

    public function getSpesifikasi(): ?string
    {
        return $this->spesifikasi;
    }

    public function setSpesifikasi(string $spesifikasi): static
    {
        $this->spesifikasi = $spesifikasi;

        return $this;
    }

    public function getKondisi(): ?string
    {
        return $this->kondisi;
    }

    public function setKondisi(string $kondisi): static
    {
        $this->kondisi = $kondisi;

        return $this;
    }

    public function getJmlMasuk(): ?int
    {
        return $this->jml_masuk;
    }

    public function setJmlMasuk(int $jml_masuk): static
    {
        $this->jml_masuk = $jml_masuk;

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Barang;
use App\Form\BarangType;
use App\Repository\BarangRepository;
use App\Repository\BarangMasukRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/dashboard')]
class DashboardController extends AbstractController
{
    #[Route('/', name: 'app_dashboard_index', methods: ['GET'])]
    public function index(BarangRepository $barangRepository): Response
    {
        return $this->render('dashboard/index.html.twig', [
            'barangs' => $barangRepository->findAll(),
        ]);
    }

    #[Route('/barang', name:'app_dashboard_barang', methods: ['GET'])]
    public function barang(BarangMasukRepository $barangMasukRepository): Response
    {
        return $this->render('dashboard/barang.html.twig', [
            'barangs' => $barangMasukRepository->findAll(),
        ]);
    }


    #[Route('/new', name: 'app_dashboard_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, Barang $barang = null): Response
    {
        $barang = new Barang();
        $form = $this->createForm(BarangType::class, $barang);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($barang);
            $entityManager->flush();

            return $this->redirectToRoute('app_dashboard_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('dashboard/new.html.twig', [
            'barang' => $barang,
            'form' => $form,
        ]);
    }

    #[Route('/{id_barang}', name: 'app_dashboard_show', methods: ['GET'])]
    public function show(Barang $barang): Response
    {
        if (!$barang) {
            throw $this->createNotFoundException('The barang does not exist');
        }

        return $this->render('dashboard/show.html.twig', [
            'barang' => $barang,
        ]);
    }

    #[Route('/{id_barang}/edit', name: 'app_dashboard_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Barang $barang, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(BarangType::class, $barang);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_dashboard_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('dashboard/edit.html.twig', [
            'barang' => $barang,
            'form' => $form,
        ]);
    }

    #[Route('/{id_barang}', name: 'app_dashboard_delete', methods: ['POST'])]
    public function delete(Request $request, Barang $barang, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$barang->getIdBarang(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($barang);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_dashboard_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/dashboard/_delete_form.html.twig
<form method="post" action="{{ path('app_dashboard_delete', {'id_barang': barang.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ barang.id) }}">
    <button class="btn">Delete</button>
</form>

templates/dashboard/_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="main-content">
    <section class="section">
        <div class="section-header">
            <h1>{{ barang.idBarang ? 'Edit Barang' : 'Tambah Barang' }}</h1>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{ barang.idBarang ? 'Edit Barang' : 'Tambah Barang' }}</h4>
                    </div>
                    <div class="card-body">
                        {{ form_start(form) }}
                        {{ form_widget(form.nama_barang, { 'attr': {'class': 'form-control'} }) }}
                        <div class="form-group text-right">
                            {% if barang.idBarang %}
                            {{ form_widget(form.save_and_continue) }}
                            {% else %}
                            {{ form_widget(form.save) }}
                            {% endif %}
                            <a href="{{ path('app_dashboard_index') }}">
                                <button type="button" class="btn btn-danger">Kembali</button>
                            </a>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

templates/dashboard/barang.html.twig
{% extends 'base.html.twig' %}

{% block title %}Barang index{% endblock %}

{% block body %}
    {{ include('layouts/header.html.twig') }}
    {{ include('layouts/navigation.html.twig') }}
    <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Barang List</h1>
          </div>

          <div class="section-body">
            <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h4>Stok Barang</h4>
                      <div class="card-header-action"><a href="{{ path('app_dashboard_new') }}"><button class="btn btn-lg btn-info" type="submit"><i class="fas fa-plus"></i> Tambah Baru</button></a></div>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>
                          <tr>
                            <th class="text-center">No</th>
                            <th>Nama Barang</th>
                            <th>Jumlah Masuk</th>
                            <th>action</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% set counter = 1 %}
                        {% for barang in barangs %}
                          <tr>
                            <td class="text-center">{{ counter }}</td>
                            {% set counter = counter + 1 %}
                            <td>
                                <span class="text-capitalize">{{ barang.barang.namaBarang }}</span>
                            </td>
                            <td><div class="badge badge-light">{{ barang.jmlMasuk }}</div></td>
                            <td>
                               <a href="{{ path('app_dashboard_edit', {'id_barang': barang.id}) }}" class="btn btn-primary btn-action mr-1" data-toggle="tooltip" title="Edit"><i class="fas fa-pencil-alt"></i></a>
                            </td>
                          </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
    </div>
    {{ include('layouts/footer.html.twig') }}
{% endblock %}

templates/dashboard/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Barang{% endblock %}

{% block body %}
    <h1>Edit Barang</h1>

    {{ include('dashboard/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_dashboard_index') }}">back to list</a>

    {{ include('dashboard/_delete_form.html.twig') }}
{% endblock %}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Barang index{% endblock %}

{% block body %}
    {# <h1>Barang index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id_barang</th>
                <th>Nama_barang</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for barang in barangs %}
            <tr>
                <td>{{ barang.idBarang }}</td>
                <td>{{ barang.namaBarang }}</td>
                <td>
                    <a href="{{ path('app_dashboard_show', {'id_barang': barang.idBarang}) }}">show</a>
                    <a href="{{ path('app_dashboard_edit', {'id_barang': barang.idBarang}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> #}
    {{ include('layouts/header.html.twig') }}
    {{ include('layouts/navigation.html.twig') }}
    <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Dashboard</h1>
          </div>

        <?php if ($level->level == 'administrator'): ?>
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-danger">
                  <i class="far fa-user"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total User</h4>
                  </div>
                  <div class="card-body"><?= $users; ?></div>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-success">
                  <i class="fas fa-archive"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Data Barang</h4>
                  </div>
                  <div class="card-body"><?= $barangs; ?></div>
                </div>
              </div>
            </div>
            <div class="col-12">
              <a href="<?php echo site_url('barang/tambahbarang/'); ?>"><button class="col-12 btn btn-lg btn-info mb-2" type="submit"><i class="fas fa-plus"></i> Barang Baru</button></a>
            </div>
          </div>
        <?php elseif ($level->level == 'manajemen'): ?>
          <div class="row">
            <div class="col-lg-12 col-md-6 col-sm-6 col-12">
              <div class="card card-statistic-1">
                <div class="card-icon bg-success">
                  <i class="fas fa-archive"></i>
                </div>
                <div class="card-wrap">
                  <div class="card-header">
                    <h4>Total Data Barang</h4>
                  </div>
                  <div class="card-body"><?= $barangs; ?></div>
                </div>
              </div>
            </div>
            <div class="col-12">
              <a href="<?php echo site_url('barang/tambahbarang/'); ?>"><button class="col-12 btn btn-lg btn-info mb-2" type="submit"><i class="fas fa-plus"></i> Barang Baru</button></a>
            </div>
          </div>
        <?php endif; ?>
          <div class="section-body">
            <div class="row">
                <div class="col-12">
                  <div class="card">
                    <div class="card-header">
                      <h4>Stok Barang</h4>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-striped" id="table-1">
                        <thead>
                          <tr>
                            <th class="text-center">No</th>
                            <th>Nama Barang</th>
                            <th>Jumlah Masuk</th>
                            <th>Jumlah Keluar</th>
                            <th>Stok Barang</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% set counter = 1 %}
                        {% for barang in barangs %}
                            <tr>
                                <td class="text-center">{{ counter }}</td>
                                {% set counter = counter + 1 %}
                                <td><span class="text-capitalize">{{ barang.namaBarang }}</span></td>
                                {# <td>
                                    <a href="{{ path('app_dashboard_show', {'id_barang': barang.idBarang}) }}">show</a>
                                    <a href="{{ path('app_dashboard_edit', {'id_barang': barang.idBarang}) }}">edit</a>
                                </td> #}
                                <td>barang.jmlMasuk</td>
                                <td>barang.jmlKeluar</td>
                                <td><div class="badge badge-primary">10</div></td>
                            </tr>
                        {% endfor %}
                 
                          {# <tr>
                            <td class="text-center"><?= $no++; ?></td>
                            <td>
                                <span class="text-capitalize"><?= $data->nama_barang; ?></span>
                            </td>
                            <td><?= $data->jml_masuk; ?></td>
                            <td><?= $data->jml_keluar; ?></td>
                            <td><div class="badge badge-primary"><?= $data->sisa_stok; ?></div></td>
                          </tr> #}

                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </section>
      </div>

    {{ include('layouts/footer.html.twig') }}


    <a href="{{ path('app_dashboard_new') }}">Create new</a>
{% endblock %}

templates/dashboard/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Barang{% endblock %}

{% block body %}
    {{ include('layouts/header.html.twig')  }}
    {{ include('layouts/navigation.html.twig') }}

    {{ include('dashboard/_form.html.twig') }}

    {{ include('layouts/footer.html.twig') }}
    
{% endblock %}

templates/dashboard/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Barang{% endblock %}

{% block body %}
    <h1>Barang</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_barang</th>
                <td>{{ barang.idBarang }}</td>
            </tr>
            <tr>
                <th>Nama_barang</th>
                <td>{{ barang.namaBarang }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_dashboard_index') }}">back to list</a>

    {# <a href="{{ path('app_dashboard_edit', {'id_barang': barang.idBarang}) }}">edit</a> #}

    {{ include('dashboard/_delete_form.html.twig') }}
{% endblock %}